# Generated by Django 3.1.6 on 2021-02-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Enter title', help_text='Post title', max_length=100),
        ),
    ]
